### ISSUE TITLE
Questions 1 2 3

### ISSUE THREAD

**Issue by GigiPoon** [firstly-colab/firstly-frontEnd#2]
map the answers on the page and create a state to hold all the data inside the array. Make the answers remain checked inside the checkbox when the user clicks on the next or back button. Make sure the array doesn't submit the answer to the backend twice. If the user submits an empty array prevent the user from pressing next. (error handling)

**Comment by Gurupriyan** [comment]
Questionnaire section created and also allows multiple selection. Approved by team members
